date_variables:
  # date variables to pass to upcoming earnings
  upcoming_earnings:
    init_offset: 1 # initial offset
    date_window: 14 # date window we want to look in
    init_unit: DAYS # default unit
    date_window_unit: DAYS # both this and init_unit use the "Unit" enum from `data_gathering.models.date_range`
  historical_data:
    from_date: "1983-01-01"
    to_date: !TODAY CURRENT_DATE
